model:
  model_name: vit_tiny_patch16_224
train_dataset:
  jpg_dir: /home/fumiyauchiyama/dataset/sa-1b/raw_jpg_1_20
  json_dir: /home/fumiyauchiyama/dataset/sa-1b/raw_json_1_20
  num_data: 223749
  max_mask_num: 2